prevent argparse from parsing iptables options
since 2f435f7a
--direct --passthrough ipv4 --table filter --delete INPUT --jump ACCEPT
has been failing with:
error: ambiguous option: --delete could match --delete-icmptype,
--delete-service, --delete-zone