fix(rich): validate service name of rich rule
Previously, validation of valid service names was not done.
That meant:

  $ firewall-cmd --add-rich-rule='rule priority="-100" family="ipv4" source address="10.0.0.10" service name="listen" accept' --permanent
  success
  $ firewall-cmd --reload
  Error: INVALID_SERVICE: listen

which left firewalld in a bad state.

Now:

  $ firewall-cmd --add-rich-rule='rule priority="-100" family="ipv4" source address="10.0.0.10" service name="listen" accept' --permanent
  Error: INVALID_SERVICE: Zone 'public': 'listen' not among existing services

https://issues.redhat.com/browse/RHEL-5790
(cherry picked from commit fbcdddd3e38c31a7b8325bf02764b84344c216b0)