Revert "firewall-config: update zoneStore also in update_active_zones()"
This reverts commit 3d7a8b7d8b6c1ae81f422e2ee1b9e50201b0b0dd

Reason for the revert is that it causes
the following traceback when removing zone:
File "firewall-config", line 2005, in onChangeZone
    settings = zone.getSettings()
AttributeError: 'NoneType' object has no attribute 'getSettings'