Re-add dropped file watcher limitation for .xml files
and extend it to .conf files as well.

It was previously dropped with 106f5872 due to
adding new watch for firewalld.conf in 32765557
but has been causing:
ERROR: INVALID_FILENAME: '/etc/firewalld/zones/public.xml.old'